---
  - name: "update packages."
    become: true
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: true
    apt:
      upgrade: yes

  - name: "Install Node.js 13"
    become: true
    shell: |
      curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
      sudo apt install -y nodejs
      sudo npm install --global n
      sudo n 13.8.0

  - name: "install pm2 globally"
    become: true
    npm:
      name: pm2
      global: yes
      production: yes
      state: present